# Generated by Django 5.2.7 on 2025-11-13 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("added_events", models.PositiveIntegerField(default=0)),
                ("updated_events", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "sync_results",
                "ordering": ["-executed_at"],
            },
        ),
    ]
