# Generated by Django 5.2.7 on 2025-11-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncresult",
            name="last_synced_event_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
