# Generated by Django 5.2.7 on 2025-11-07 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3b07f19d-d095-4e98-95bd-bedd4cc22948"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="eventvenue",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8d6a6139-eb4e-4c74-83bc-a634bd0ed977"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterModelTable(
            name="event",
            table="events",
        ),
    ]
