# Generated by Django 5.2.7 on 2025-11-14 23:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventregistration"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_events",
            },
        ),
    ]
